### ISSUE TITLE
Pull request for projects

### ISSUE THREAD

**Issue by neortega25** [NeuroHackademy2024/BIDSInspec#8]
Dr. Ariel: o add your project, please edit the README.md file, following the template at the top and make a pull request with your project's information. Please reach out if you run into any issues.

**Comment by arokem** [comment]
Make a pull request to this repo: https://github.com/NeuroHackademy2024/projects 😄

**Comment by neortega25** [comment]
Yes, sorry I was just adding the task to our to do list. Sorry about the confusion.

**Comment by arokem** [comment]
No worries! Just making sure you have the link right here where you might need it 🚀
